config/routes.rb
MelhoresPratos::Application.routes.draw do
  namespace :panel do
    resources :restaurants do
      member do
        post :publish
      end
      resources :foods
      resources :menu_categories
    end
  end

  resources :cities
  resources :cuisines
  resources :restaurants, only: [:show]

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root to: 'site#home'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  mount_uploader :logo, RestaurantLogoUploader
  mount_uploader :cover, RestaurantCoverUploader

  belongs_to :city
  belongs_to :user
  has_many :menu_categories
  has_many :foods, through: :menu_categories

  validates :name, presence: true
  validates :slug, presence: true, uniqueness: true
  validates :zip_code, presence: true
  validates :street, presence: true
  validates :street_number, presence: true
  validates :neighborhood, presence: true
  validates :city, presence: true

  delegate :state, to: :city

  scope :published, -> { where("published_at IS NOT NULL").order("published_at DESC") }

end

app/controllers/panel/base_controller.rb
class Panel::BaseController < ApplicationController

  before_filter :authenticate_user!

  def load_restaurant
    @restaurant = current_user.restaurants.find(params[:restaurant_id] || params[:id])
  end

  def food_params
    params
      .require(:food)
      .permit(:name, :description, :photo, :special, :menu_category_id, :cuisine_tokens,
        portions_attributes: [:id, :size, :price, :_destroy]
      )
  end

  def menu_category_params
    params
      .require(:menu_category)
      .permit(:name, :description)
  end

  def restaurant_params
    params
      .require(:restaurant)
      .permit(:name, :slug, :zip_code, :street, :street_number, :neighborhood, :complement, :city_id,
        :description, :website, :phone_number, :extra_phone_number, :logo, :cover)
  end
end

app/controllers/panel/foods_controller.rb
class Panel::FoodsController < Panel::BaseController

  before_filter :load_restaurant
  before_filter :load_food, except: [:index, :create]
  before_filter :load_category, except: :destroy

  def index
    @food = Food.new
  end

  def create
    @food = @restaurant.foods.new(food_params)
    @food.save
  end

  def edit
  end

  def update
    @food.update_attributes(food_params)
  end

  def destroy
    @food.destroy

    redirect_to panel_restaurant_foods_path(@restaurant), notice: I18n.t("panel.foods.destroy")
  end

  private

  def load_food
    @food = @restaurant.foods.find(params[:id])
  end

  def load_category
    @menu_category = MenuCategory.new
  end
end

app/controllers/panel/menu_categories_controller.rb
class Panel::MenuCategoriesController < Panel::BaseController

  before_filter :load_restaurant
  before_filter :load_food, only: [:show, :create]
  before_filter :load_category, except: [:create]

  def show
    @new_category = MenuCategory.new
  end

  def create
    @menu_category = @restaurant.menu_categories.new(menu_category_params)
    @menu_category.save
  end

  def edit
  end

  def update
    @menu_category.update_attributes(menu_category_params)
  end

  def destroy
    @menu_category.destroy

    redirect_to panel_restaurant_foods_path(@restaurant), notice: I18n.t("panel.menu_categories.destroy")
  end

  private

  def load_category
    @menu_category = @restaurant.menu_categories.find(params[:id])
  end

  def load_food
    @food = Food.new
  end
end

app/controllers/panel/restaurants_controller.rb
class Panel::RestaurantsController < Panel::BaseController

  before_filter :load_restaurant, except: [:index, :new, :create]

  def index
    @restaurants = current_user.restaurants
  end

  def show
  end

  def new
    @restaurant = current_user.restaurants.new
  end

  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.create")
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.update")
    else
      render :edit
    end
  end

  def publish
    published_at = @restaurant.published_at ? nil : Time.current
    @restaurant.update_attributes(published_at: published_at)

    redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.publish")
  end

  def destroy
    @restaurant.destroy
    redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.destroy")
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def show
    @restaurant = Restaurant.find(params[:id]).decorate
  end

end

app/views/panel/restaurants/_form.html.haml
%table.central-table-form
  = hidden_field_tag :latitude
  = hidden_field_tag :longitude

  %tr
    %td{colspan: "2"}
      %h5 Informações Básicas
  %tr
    %th
      = f.label :name, "Nome:"
    %td
      .control-group
        .controls
          = f.text_field :name, class: "span6"
  %tr
    %th
      = f.label :slug, "URL:"
    %td
      .control-group
        .controls
          .input-prepend
            %span.add-on melhorespratos.com.br/
            = f.text_field :slug, class: "span-url"
  %tr
    %td{colspan: "2"}
      %h5 Informações de Contato
  %tr
    %th
      = f.label :zip_code, "CEP:"
    %td
      .control-group
        .controls
          = f.text_field :zip_code, class: "span6 cep"
          %span.help-inline
            = link_to "Não sabe ceu CEP? Clique aqui", "http://www.buscacep.correios.com.br/", target: :blank
  %tr
    %th
      = f.label :street, "Endereço:"
    %td
      .control-group
        .controls
          = f.text_field :street, class: "span5 margin-right-20"
          = f.text_field :street_number, class: "span1", placeholder: "Nº"
  %tr
    %th
      = f.label :neighborhood, "Bairro:"
    %td
      .control-group
        .controls
          = f.text_field :neighborhood, class: "span6"
  %tr
    %th
      = f.label :complement, "Complemento:"
    %td
      .control-group
        .controls
          = f.text_field :complement, class: "span6"
  %tr
    %th
      = label_tag :state, "Estado:"
    %td
      .control-group
        .controls
          = select_tag :state, options_for_select(State.all.map{ |s| [s.name, s.id, { data: { acronym: s.acronym } } ] }, f.object.try(:city).try(:state_id)), include_blank: true, class: "span6"
  %tr
    %th
      = label_tag :city, "Cidade:"
    %td
      .control-group
        .controls
          = f.select :city_id, options_from_collection_for_select(City.all, :id, :name, f.object.city_id), {include_blank: true}, class: "span6"
  %tr
    %th
      = f.label :phone_number, "Telefones:"
    %td
      .control-group
        .controls
          = f.text_field :phone_number, class: "span3 phone margin-right-20"
          = f.text_field :extra_phone_number, class: "span3 phone"
  %tr
    %td{colspan: "2"}
      %h5 Detalhes do Estabelecimento
  %tr
    %th
      = f.label :description, "Descrição:"
    %td
      .control-group
        .controls
          = f.text_area :description, class: "span6"
  %tr
    %th
      = f.label :website, "Site:"
    %td
      .control-group
        .controls
          = f.text_field :website, class: "span6"
  %tr
    %th
      = f.label :logo, "Logo:"
    %td
      .control-group
        .controls
          %span.prettyFile
            = f.file_field :logo
            .input-append
              %input.input-large{type: "text"}/
              %a.btn{href: "#"} Escolher Arquivo

  %tr
    %th
      = f.label :cover, "Capa:"
    %td
      .control-group
        .controls
          %span.prettyFile
            = f.file_field :cover
            .input-append
              %input.input-large{type: "text"}/
              %a.btn{href: "#"} Escolher Arquivo

  %tr
    %th
    %td
      = f.button class: "btn btn-large btn-theme span6 no-margin" do
        %i.icon-plus-sign
        Salvar Estabelecimento

app/views/panel/restaurants/_menu_info.html.haml
.span12
  %article.blog-post
    .post-heading
      %h3 Editar Cardápio
  %ul.media-list.mo-border-bottom
    %li.media
      %a.pull-left.thumbnail{href: "#"}
        = image_tag @restaurant.logo_url(:thumb_125), class: "media-object"
      .media-body
        %h5.media-heading
          = link_to @restaurant.name
        %p
          = @restaurant.description
        %ul#0002.post-meta.comments
          %li.first
            %i.icon-map-marker
            = @restaurant.street
          %li.last
            %span
              %i.icon-phone
              = @restaurant.phone_number
            %br/

app/views/panel/restaurants/_restaurant.html.haml
%tr
  %td
    = link_to "#", class: "thumbnail" do
      = image_tag restaurant.logo_url(:thumb_100), alt: restaurant.name
  %td= restaurant.name
  %td 12
  %td #{restaurant.neighborhood}, #{restaurant.city.name}
  %td= restaurant.phone_number
  %td
    = link_to panel_restaurant_foods_path(restaurant), class: "btn btn-theme", rel: "tooltip", title: "Editar Cardápio", data: { placement: "right" } do
      %i.icon-food
    %br/
    %br/
    = link_to edit_panel_restaurant_path(restaurant), class: "btn btn-theme", rel: "tooltip", title: "Configurações", data: { placement: "right" } do
      %i.icon-cog
    %br/
    %br/
    = link_to publish_panel_restaurant_path(restaurant), method: :post, class: "btn btn-theme", rel: "tooltip", title: "Publicar Cardápio", data: { placement: "right" } do
      %i.icon-cog

app/views/panel/restaurants/edit.html.haml
.row
  .span12
    %article.blog-post
      .post-heading
        %h3 Editar Estabelecimento
    = render "shared/error_messages", resource: @restaurant
    = form_for @restaurant, url: panel_restaurant_path(@restaurant), html: { method: :put, id: "estabelecimentoform" } do |f|
      = render "form", f: f

app/views/panel/restaurants/index.html.haml
.row
  %article.blog-post
    .post-heading
      %h3
        Meus Estabelecimentos
        = link_to new_panel_restaurant_path, class: "btn btn-mini btn-theme favorite-menu" do
          %i.icon-plus-sign
          Novo Estabelecimento
  .span12
    %table.table.table-striped
      %thead
        %tr
          %th
            %i.icon-picture
          %th Nome do Estabelecimento
          %th Recomendações
          %th Endereço
          %th.span2 Contato
          %th.span1 Opções
      %tbody
        = render @restaurants

app/views/panel/restaurants/new.html.haml
.row
  .span12
    %article.blog-post
      .post-heading
        %h3 Novo Estabelecimento
    = render "shared/error_messages", resource: @restaurant
    = form_for @restaurant, url: panel_restaurants_path, html: { id: "estabelecimentoform" } do |f|
      = render "form", f: f