config/routes.rb
MelhoresPratos::Application.routes.draw do
  namespace :panel do
    resources :restaurants do
      member do
        post :publish
      end
      resources :foods
      resources :menu_categories
    end
  end

  resources :cities
  resources :cuisines
  resources :restaurants, only: [:show]

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root to: 'site#home'
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
  :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  mount_uploader :avatar, UserAvatarUploader

  has_many :restaurants
  has_many :social_accounts, dependent: :destroy

  validates :name, presence: true

  def apply_omniauth(auth)
    self.name = auth['info']['name']
    self.remote_avatar_url = auth['info']['image']

    social_accounts.build(provider: auth['provider'],
                          uid: auth['uid'],
                          token: auth['credentials']['token'],
                          secret: auth['credentials']['secret'])
  end

  def password_required?
    super && (new_record? || encrypted_password.present?)
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/views/users/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/