config/routes.rb
MelhoresPratos::Application.routes.draw do
  namespace :panel do
    resources :restaurants do
      member do
        post :publish
      end
      resources :foods
      resources :menu_categories
    end
  end

  resources :cities
  resources :cuisines
  resources :restaurants, only: [:show]

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root to: 'site#home'
end

app/models/food.rb
class Food < ActiveRecord::Base

  mount_uploader :photo, FoodPhotoUploader

  belongs_to :menu_category, counter_cache: true
  has_and_belongs_to_many :cuisines
  has_many :portions

  validates :name, presence: true
  validates :menu_category, presence: true

  accepts_nested_attributes_for :portions, allow_destroy: true

  attr_reader :cuisine_tokens

  def cuisine_tokens=(tokens)
    self.cuisine_ids = Cuisine.ids_from_tokens(tokens)
  end

end

app/controllers/panel/base_controller.rb
class Panel::BaseController < ApplicationController

  before_filter :authenticate_user!

  def load_restaurant
    @restaurant = current_user.restaurants.find(params[:restaurant_id] || params[:id])
  end

  def food_params
    params
      .require(:food)
      .permit(:name, :description, :photo, :special, :menu_category_id, :cuisine_tokens,
        portions_attributes: [:id, :size, :price, :_destroy]
      )
  end

  def menu_category_params
    params
      .require(:menu_category)
      .permit(:name, :description)
  end

  def restaurant_params
    params
      .require(:restaurant)
      .permit(:name, :slug, :zip_code, :street, :street_number, :neighborhood, :complement, :city_id,
        :description, :website, :phone_number, :extra_phone_number, :logo, :cover)
  end
end

app/controllers/panel/foods_controller.rb
class Panel::FoodsController < Panel::BaseController

  before_filter :load_restaurant
  before_filter :load_food, except: [:index, :create]
  before_filter :load_category, except: :destroy

  def index
    @food = Food.new
  end

  def create
    @food = @restaurant.foods.new(food_params)
    @food.save
  end

  def edit
  end

  def update
    @food.update_attributes(food_params)
  end

  def destroy
    @food.destroy

    redirect_to panel_restaurant_foods_path(@restaurant), notice: I18n.t("panel.foods.destroy")
  end

  private

  def load_food
    @food = @restaurant.foods.find(params[:id])
  end

  def load_category
    @menu_category = MenuCategory.new
  end
end

app/controllers/panel/menu_categories_controller.rb
class Panel::MenuCategoriesController < Panel::BaseController

  before_filter :load_restaurant
  before_filter :load_food, only: [:show, :create]
  before_filter :load_category, except: [:create]

  def show
    @new_category = MenuCategory.new
  end

  def create
    @menu_category = @restaurant.menu_categories.new(menu_category_params)
    @menu_category.save
  end

  def edit
  end

  def update
    @menu_category.update_attributes(menu_category_params)
  end

  def destroy
    @menu_category.destroy

    redirect_to panel_restaurant_foods_path(@restaurant), notice: I18n.t("panel.menu_categories.destroy")
  end

  private

  def load_category
    @menu_category = @restaurant.menu_categories.find(params[:id])
  end

  def load_food
    @food = Food.new
  end
end

app/controllers/panel/restaurants_controller.rb
class Panel::RestaurantsController < Panel::BaseController

  before_filter :load_restaurant, except: [:index, :new, :create]

  def index
    @restaurants = current_user.restaurants
  end

  def show
  end

  def new
    @restaurant = current_user.restaurants.new
  end

  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.create")
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.update")
    else
      render :edit
    end
  end

  def publish
    published_at = @restaurant.published_at ? nil : Time.current
    @restaurant.update_attributes(published_at: published_at)

    redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.publish")
  end

  def destroy
    @restaurant.destroy
    redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.destroy")
  end
end

app/views/panel/foods/_food.html.haml
%li.media
  .media-body
    .media
      %a.pull-left{href: "#"}
        = image_tag food.photo_url(:thumb_50), alt: "", class: "media-object img-polaroid"
      .media-body
        %h5.media-heading
          %a{href: "#"}= food.name
          .right-buttons
            %small
              = "#{link_to 'Editar', edit_panel_restaurant_food_path(@restaurant.id, food.id)} | #{link_to 'Apagar', panel_restaurant_food_path(@restaurant.id, food.id), method: :delete unless food.new_record?}".html_safe

        %p
          = food.description
        %ul#0001.post-meta.best
          %li.first
            %i.icon-chevron-down
            %span
              %a{href: "#"} 12 usuários recomendam
        / Nested media object
        .clearfix
        #best-dish-0001.media-noborder.best-dish
          %ul.thumbnails
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
            %li
              %a.thumbnail{href: "#"}
                %img{alt: "", src: "assets/avatar-usuario-thumb.jpg"}/
          %br/
          .clearfix
          %ul#0001.post-meta.comments
            %li.first
              %span 2 comentários
            %li.last
              %a{href: ""} Ver todos
          .clearfix
          #comments-dish-0001.media-noborder.comments-dish
            %ul.media-list
              %li.media-borderbottom
                %a.pull-left.thumbnail{href: "#"}
                  %img.media-object{alt: "Penélope Barbosa", "data-content" => "<strong>Total de Recomendações: </strong> 132 <br /> <strong>Membro desde: </strong> 13 de Janeiro de 2012 <br /> <strong>Cidade: </strong> João Pessoa", "data-original-title" => "<img src='assets/avatar-usuario-thumb.jpg' /> <strong>Penélope Barbosa</strong>", "data-rel" => "popover", src: "assets/avatar-usuario-thumb.jpg"}/
                .media-body
                  %h5.media-heading
                    %a{href: "#"} Mike sullivan
                    %span 3 March, 2013
                  %p
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
              %li.media-borderbottom
                %a.pull-left.thumbnail{href: "#"}
                  %img.media-object{alt: "Penélope Barbosa", "data-content" => "<strong>Total de Recomendações: </strong> 132 <br /> <strong>Membro desde: </strong> 13 de Janeiro de 2012 <br /> <strong>Cidade: </strong> João Pessoa", "data-original-title" => "<img src='assets/avatar-usuario-thumb.jpg' /> <strong>Penélope Barbosa</strong>", "data-rel" => "popover", src: "assets/avatar-usuario-thumb.jpg"}/
                .media-body
                  %h5.media-heading
                    %a{href: "#"} Mike sullivan
                    %span 3 March, 2013
                  %p
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.

app/views/panel/foods/_form.html.haml
.control-group
  = f.label :name, "Nome", class: "control-label"
  .controls
    = f.text_field :name, class: "span6"
.control-group
  %p.custom-check.controls
    = f.check_box :special
    = f.label :special, "Esse prato é uma especialidade da casa"
.control-group
  = f.label :description, "Descrição", class: "control-label"
  .controls
    = f.text_area :description, class: "span6"
.control-group
  = f.label :photo, "Imagem", class: "control-label"
  .controls
    %span.prettyFile
      = f.file_field :photo
      .input-append
        %input.input-large{type: "text"}/
        %a.btn{href: "#"} Escolher Arquivo
.control-group
  = f.label :cuisine_tokens, "Cozinhas", class: "control-label"
  .controls{style: "height: 25px"}
    = f.text_field :cuisine_tokens, class: "span6", data: { load: f.object.cuisines }
.control-group
  = f.label :menu_category_id, "Categoria", class: "control-label"
  .controls
    = f.select :menu_category_id, options_from_collection_for_select(@restaurant.menu_categories, :id, :name, f.object.menu_category_id), { include_blank: true }, class: "span6"
.control-group
  %label.control-label Preços
  .controls
    = f.fields_for :portions do |portion_form|
      .row-fluid
        .span4 Descrição
        .span4.offset1 Preço
      .row-fluid
        .span4
          = portion_form.text_field :size, class: "span12"
        .span4.offset1
          .input-prepend
            %span.add-on R$
            = portion_form.text_field :price, class: "span12"
      .row-fluid
        .span12= portion_form.link_to_remove "Remover preço"
    .row-fluid
      .span12
        = f.link_to_add :portions do
          %button.btn
            %i.icon-plus-sign
            Adicionar Preço

.row-fluid
  .span12
    %button.btn.btn-large.btn-block.btn-theme
      %i.icon-plus-sign>
      #{f.object.new_record? ? 'Adicionar Prato' : 'Atualizar Prato'}

app/views/panel/foods/create.js.haml
- if @food.valid?
  location.href = "#{panel_restaurant_foods_path(@restaurant)}";
- else
  $("#food_errors").html("#{escape_javascript(render 'shared/error_messages', resource: @food)}");

app/views/panel/foods/edit.html.haml
.row
  = render "panel/restaurants/menu_info"
  = render "panel/menu_categories/sidebar", menu_category: @menu_category

  .span8
    %article.blog-post
      .post-heading
        %h3
          Todos os Pratos
    %ul.media-list.media-list-sub-item
      = render partial: "panel/foods/food", collection: @restaurant.foods

  .span8
    %article.blog-post
      .post-heading
        %h3
          Editar Prato

    #food_errors= render "shared/error_messages", resource: @food
    = nested_form_for @food, url: panel_restaurant_food_path(@restaurant, @food), remote: true, html: { class: "form-horizontal food-form" } do |f|
      = render "panel/foods/form", f: f

app/views/panel/foods/index.html.haml
.row
  = render "panel/restaurants/menu_info"
  = render "panel/menu_categories/sidebar", menu_category: @menu_category

  .span8
    %article.blog-post
      .post-heading
        %h3
          Todos os Pratos
    %ul.media-list.media-list-sub-item
      = render partial: "panel/foods/food", collection: @restaurant.foods

  .span8
    %article.blog-post
      .post-heading
        %h3
          Cadastrar Prato

    #food_errors= render "shared/error_messages", resource: @food
    = nested_form_for @food, url: panel_restaurant_foods_path(@restaurant), remote: true, html: { class: "form-horizontal food-form"} do |f|
      = render "panel/foods/form", f: f

app/views/panel/foods/update.js.haml
- if @food.valid?
  location.href = "#{panel_restaurant_foods_path(@restaurant)}";
- else
  $("#food_errors").html("#{escape_javascript(render 'shared/error_messages', resource: @food)}");