config/routes.rb
MelhoresPratos::Application.routes.draw do
  namespace :panel do
    resources :restaurants do
      member do
        post :publish
      end
      resources :foods
      resources :menu_categories
    end
  end

  resources :cities
  resources :cuisines
  resources :restaurants, only: [:show]

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root to: 'site#home'
end

app/models/menu_category.rb
class MenuCategory < ActiveRecord::Base

  belongs_to :restaurant
  has_many :foods, dependent: :destroy

  validates :name, presence: true
end

app/controllers/panel/base_controller.rb
class Panel::BaseController < ApplicationController

  before_filter :authenticate_user!

  def load_restaurant
    @restaurant = current_user.restaurants.find(params[:restaurant_id] || params[:id])
  end

  def food_params
    params
      .require(:food)
      .permit(:name, :description, :photo, :special, :menu_category_id, :cuisine_tokens,
        portions_attributes: [:id, :size, :price, :_destroy]
      )
  end

  def menu_category_params
    params
      .require(:menu_category)
      .permit(:name, :description)
  end

  def restaurant_params
    params
      .require(:restaurant)
      .permit(:name, :slug, :zip_code, :street, :street_number, :neighborhood, :complement, :city_id,
        :description, :website, :phone_number, :extra_phone_number, :logo, :cover)
  end
end

app/controllers/panel/foods_controller.rb
class Panel::FoodsController < Panel::BaseController

  before_filter :load_restaurant
  before_filter :load_food, except: [:index, :create]
  before_filter :load_category, except: :destroy

  def index
    @food = Food.new
  end

  def create
    @food = @restaurant.foods.new(food_params)
    @food.save
  end

  def edit
  end

  def update
    @food.update_attributes(food_params)
  end

  def destroy
    @food.destroy

    redirect_to panel_restaurant_foods_path(@restaurant), notice: I18n.t("panel.foods.destroy")
  end

  private

  def load_food
    @food = @restaurant.foods.find(params[:id])
  end

  def load_category
    @menu_category = MenuCategory.new
  end
end

app/controllers/panel/menu_categories_controller.rb
class Panel::MenuCategoriesController < Panel::BaseController

  before_filter :load_restaurant
  before_filter :load_food, only: [:show, :create]
  before_filter :load_category, except: [:create]

  def show
    @new_category = MenuCategory.new
  end

  def create
    @menu_category = @restaurant.menu_categories.new(menu_category_params)
    @menu_category.save
  end

  def edit
  end

  def update
    @menu_category.update_attributes(menu_category_params)
  end

  def destroy
    @menu_category.destroy

    redirect_to panel_restaurant_foods_path(@restaurant), notice: I18n.t("panel.menu_categories.destroy")
  end

  private

  def load_category
    @menu_category = @restaurant.menu_categories.find(params[:id])
  end

  def load_food
    @food = Food.new
  end
end

app/controllers/panel/restaurants_controller.rb
class Panel::RestaurantsController < Panel::BaseController

  before_filter :load_restaurant, except: [:index, :new, :create]

  def index
    @restaurants = current_user.restaurants
  end

  def show
  end

  def new
    @restaurant = current_user.restaurants.new
  end

  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.create")
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.update")
    else
      render :edit
    end
  end

  def publish
    published_at = @restaurant.published_at ? nil : Time.current
    @restaurant.update_attributes(published_at: published_at)

    redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.publish")
  end

  def destroy
    @restaurant.destroy
    redirect_to panel_restaurants_path, notice: I18n.t("panel.restaurants.destroy")
  end
end

app/views/panel/menu_categories/_form.html.haml
= f.label :name, "Nome da Categoria"
= f.text_field :name
= f.label :description, "Descrição"
= f.text_area :description
= f.button class: "btn btn-large btn-block btn-theme" do
  %i.icon-plus-sign
  Adicionar Categoria

app/views/panel/menu_categories/_sidebar.html.haml
.span4
  %aside
    .widget
      %h4.rheading
        Categorias
        %span
      %ul#categoria-sortable.side-list
        %li= link_to "Todos os pratos (#{@restaurant.foods.count})", panel_restaurant_foods_path(@restaurant)
        - @restaurant.menu_categories.each do |category|
          %li
            = link_to "#{category.name} (#{category.foods_count})", panel_restaurant_menu_category_path(@restaurant, category) unless category.new_record?
      #new_category_errors= render "shared/error_messages", resource: menu_category
      = form_for menu_category, url: panel_restaurant_menu_categories_path, html: { id: "categoriaform", remote: true } do |f|
        = render "panel/menu_categories/form", f: f

app/views/panel/menu_categories/create.js.haml
- if @menu_category.valid?
  location.href = "#{panel_restaurant_menu_category_path(@restaurant, @menu_category)}";
- else
  $("#new_category_errors").html("#{escape_javascript(render 'shared/error_messages', resource: @menu_category)}");

app/views/panel/menu_categories/show.html.haml
.row
  = render "panel/restaurants/menu_info"
  = render "panel/menu_categories/sidebar", menu_category: @new_category

  .span8
    %article.blog-post
      %p.text-right
        = link_to "Editar Categoria", "#edit", class: "btn btn-theme", data: { toggle: "modal" }
        = link_to "Remover Categoria", "#delete", class: "btn btn-theme", data: { toggle: "modal" }

      .post-heading
        %h3
          Pratos
          %i.icon-chevron-right{style: "font-size:18px"}
          = @menu_category.name

    %ul.media-list.media-list-sub-item
      = render partial: "panel/foods/food", collection: @menu_category.foods

  .span8
    %article.blog-post
      .post-heading
        %h3
          Cadastrar Prato

    #food_errors= render "shared/error_messages", resource: @food
    = nested_form_for @food, url: panel_restaurant_foods_path(@restaurant), remote: true, html: { class: "form-horizontal food-form" } do |f|
      = render "panel/foods/form", f: f

#delete.modal.hide.fade
  .modal-header
    %button.close{ data: { dismiss: "modal" } } ×
    %h3 Remover Categoria
  .modal-body
    %p Ao remover a categoria, todos os pratos serao destruidos. Deseja continuar?
  .modal-footer
    = link_to "Sim, Remover Categoria", panel_restaurant_menu_category_path(@restaurant, @menu_category), method: :delete, class: "btn btn-theme"
    = link_to "Voltar", "#", class: "btn", data: { dismiss: "modal" }

#edit.modal.hide.fade
  .modal-header
    %button.close{ data: { dismiss: "modal" } } ×
    %h3 Editar Categoria
  .modal-body
    #category_errors
      = render "shared/error_messages", resource: @menu_category
    = form_for @menu_category, url: panel_restaurant_menu_category_path(@restaurant, @menu_category), html: { class: "form-horizontal", remote: true } do |f|
      .control-group
        = f.label :name, "Nome", class: "control-label"
        .controls
          = f.text_field :name, class: "span5"
      .control-group
        = f.label :description, "Descrição", class: "control-label"
        .controls
          = f.text_area :description, class: "span5"
      .row-fluid
        .span12
          = f.button class: "btn btn-large btn-block btn-theme" do
            %i.icon-plus-sign
            Atualizar Categoria

app/views/panel/menu_categories/update.js.haml
- if @menu_category.valid?
  location.href = "#{panel_restaurant_menu_category_path(@restaurant, @menu_category)}";
- else
  $("#category_errors").html("#{escape_javascript(render 'shared/error_messages', resource: @menu_category)}");